# Generated by Django 4.2.3 on 2023-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
