# Generated by Django 4.2.3 on 2023-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='customer', max_length=150),
        ),
    ]
