# Generated by Django 4.2.3 on 2023-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
