# Generated by Django 4.2.3 on 2023-08-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0012_alter_basket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
